<?php

declare(strict_types=1);

namespace Database\Seeders\SkillsData;

/**
 * Pack 2 — 5 testes de soft skills e carreira.
 * Atendimento ao Cliente, Vendas, Comunicação Profissional,
 * LinkedIn na Prática, Rotinas Administrativas.
 *
 * Estrutura de cada questão: [enunciado, [4 opções], índice correto (0-3), explicação].
 */
final class SkillPack2
{
    public static function data(): array
    {
        return [
            /* ============================================================
             |  6) ATENDIMENTO AO CLIENTE
             |============================================================ */
            [
                'title' => 'Atendimento ao Cliente',
                'slug'  => 'atendimento-ao-cliente',
                'category' => 'Vendas & Atendimento',
                'short_description' => 'Como resolver problemas, encantar e reter clientes com excelência.',
                'description' => 'Princípios do atendimento profissional: escuta ativa, empatia, resolução de reclamações, SAC 4.0 e Código de Defesa do Consumidor básico.',
                'difficulty' => 'basic',
                'icon' => 'message', 'color' => 'brand',
                'questions' => [
                    ['Um cliente irritado começa a gritar ao telefone. A primeira atitude correta é:',
                        ['Desligar imediatamente', 'Escutar sem interromper e demonstrar empatia', 'Elevar o tom para se impor', 'Transferir para outro atendente'], 1,
                        'Escuta ativa acalma o cliente. Interromper ou revidar piora a situação. Empatia é a base do atendimento.'],
                    ['O que significa "empatia" no atendimento?',
                        ['Concordar com tudo que o cliente diz', 'Se colocar no lugar do cliente e entender a dor dele', 'Ser educado e sorrir sempre', 'Prometer resolver mesmo sem poder'], 1,
                        'Empatia = compreender o sentimento do outro. Não é concordância, é compreensão genuína.'],
                    ['Segundo o CDC, o prazo para reclamar de produto durável defeituoso é:',
                        ['30 dias', '60 dias', '90 dias', '180 dias'], 2,
                        'CDC Art. 26: 30 dias para produtos não duráveis, 90 dias para duráveis (eletrodomésticos, móveis).'],
                    ['SLA no atendimento significa:',
                        ['Serviço Livre de Atendimento', 'Acordo de Nível de Serviço (tempo máximo de resposta)', 'Sistema Local de Atendimento', 'Suporte Limitado ao Assinante'], 1,
                        'SLA (Service Level Agreement) define o tempo/qualidade prometido no atendimento.'],
                    ['Qual expressão é INADEQUADA num atendimento?',
                        ['"Vou verificar isso agora mesmo"', '"Entendi sua situação"', '"Isso não é problema meu"', '"Vou resolver junto com você"'], 2,
                        'Nunca terceirize responsabilidade. Mesmo se não for sua área, seja intermediário.'],
                    ['Um cliente pede algo impossível. Você deve:',
                        ['Prometer para não perdê-lo', 'Recusar sem dar alternativa', 'Dizer que não pode + oferecer o que é possível', 'Fingir que não ouviu'], 2,
                        'Nunca prometa o que não pode cumprir. Sempre ofereça uma alternativa realista.'],
                    ['NPS (Net Promoter Score) mede:',
                        ['Lucro por cliente', 'Quantos clientes recomendariam a empresa', 'Volume de chamadas', 'Tempo de atendimento'], 1,
                        'NPS pergunta "de 0 a 10, quanto você recomendaria?" e mede lealdade do cliente.'],
                    ['No chat/WhatsApp da empresa, o tempo ideal para primeira resposta é:',
                        ['Até 24 horas', 'Até 1 hora', 'Até 5 minutos', 'Só quando puder'], 2,
                        'No digital, cliente espera resposta quase imediata. 5 min é o padrão de excelência.'],
                    ['Cliente reclama de um erro que a EMPRESA cometeu. O correto é:',
                        ['Culpar o setor responsável na frente dele', 'Assumir a responsabilidade em nome da empresa e resolver', 'Dizer que não sabia do erro', 'Pedir para reclamar formalmente por escrito'], 1,
                        'Nunca "jogue" para outra área na frente do cliente. Assuma como empresa e resolva.'],
                    ['A técnica LATTE (Starbucks) inclui:',
                        ['Listen, Acknowledge, Take action, Thank, Explain', 'Lead, Ask, Talk, Try, End', 'Learn, Ask, Test, Teach, Evaluate', 'Look, Answer, Try, Thank, Escalate'], 0,
                        'LATTE: Escute → Reconheça → Aja → Agradeça → Explique. Método clássico de recuperação.'],
                    ['Ao encerrar um atendimento você deve:',
                        ['Só desligar', 'Confirmar se ficou alguma dúvida e se despedir educadamente', 'Perguntar se ele vai continuar cliente', 'Mandar um formulário longo'], 1,
                        'Sempre confirme resolução e agradeça. Deixa boa impressão final.'],
                    ['Um cliente pede desconto que você não pode dar. Melhor abordagem:',
                        ['Insistir que o preço é justo', 'Reconhecer a solicitação e oferecer valor agregado (brinde, frete grátis)', 'Ignorar o pedido', 'Chamar o gerente sempre'], 1,
                        'Se não pode dar desconto, ofereça algo de valor: benefício, brinde, condição especial.'],
                    ['O "Momento da verdade" no atendimento é:',
                        ['A hora do pagamento', 'Todo contato do cliente com a empresa', 'A avaliação anual', 'A propaganda'], 1,
                        'Cada interação (do site à entrega) é um "momento da verdade" — molda a percepção do cliente.'],
                    ['CRM significa:',
                        ['Central de Reclamações Mensais', 'Gestão de Relacionamento com o Cliente', 'Controle de Retorno de Mercadoria', 'Custo de Reembolso Máximo'], 1,
                        'CRM (Customer Relationship Management) organiza dados e histórico do cliente.'],
                    ['Ao registrar um chamado, você deve incluir:',
                        ['Só o nome do cliente', 'Nome, contato, descrição detalhada do problema e prioridade', 'Só a solução aplicada', 'Apenas a data'], 1,
                        'Registro completo permite qualquer atendente futuro entender o caso. Fundamental para SAC.'],
                    ['A diferença entre atendimento REATIVO e PROATIVO:',
                        ['Reativo é mais rápido', 'Proativo é antecipar necessidades antes do cliente reclamar', 'Não há diferença', 'Proativo é mais barato'], 1,
                        'Proativo: você entra em contato antes do problema estourar. Ex: aviso de atraso antes da reclamação.'],
                    ['Cliente pede algo fora de política, mas tem razão emocional. Ideal:',
                        ['Recusar de forma seca', 'Escalar para um supervisor com poder de exceção', 'Dizer "não podemos" 10 vezes', 'Encerrar o atendimento'], 1,
                        'Casos especiais existem. Encaminhe para quem pode tomar decisão de exceção.'],
                    ['O "efeito Halo" no atendimento é:',
                        ['Auréola de luz nas lojas', 'Uma boa experiência em um ponto influencia percepção geral', 'Bônus salarial dos atendentes', 'Nome do software'], 1,
                        'Uma experiência memorável (positiva ou negativa) contamina a avaliação de tudo mais.'],
                    ['Ao lidar com reclamação nas redes sociais (pública), o correto é:',
                        ['Ignorar', 'Deletar o comentário', 'Responder publicamente com empatia e levar solução para o privado', 'Bloquear o cliente'], 2,
                        'Responda em público mostrando cuidado, mas resolva em canal privado. Outros clientes estão vendo.'],
                    ['A frase mais adequada ao começar um atendimento é:',
                        ['"Alô?"', '"Diga aí!"', '"Olá, meu nome é X, como posso ajudar?"', '"Fala aê"'], 2,
                        'Sempre saúde, apresente-se e coloque-se à disposição. Personaliza e profissionaliza.'],
                ],
            ],

            /* ============================================================
             |  7) VENDAS
             |============================================================ */
            [
                'title' => 'Técnicas de Vendas',
                'slug'  => 'tecnicas-de-vendas',
                'category' => 'Vendas & Atendimento',
                'short_description' => 'Prospecção, argumentação, quebra de objeções e fechamento.',
                'description' => 'Fundamentos de vendas B2C e B2B: SPIN Selling, quebra de objeções, gatilhos mentais éticos e follow-up.',
                'difficulty' => 'intermediate',
                'icon' => 'trophy', 'color' => 'amber',
                'questions' => [
                    ['A sigla SPIN (metodologia de vendas) significa:',
                        ['Situação, Problema, Implicação, Necessidade', 'Sales, Price, Interest, Negotiation', 'Serviço, Preço, Imagem, Notoriedade', 'Sistema, Plano, Ideal, Novo'], 0,
                        'SPIN Selling (Neil Rackham) usa 4 tipos de perguntas para vendas complexas.'],
                    ['A regra 80/20 (Pareto) nas vendas diz que:',
                        ['80% dos clientes reclamam', '80% do faturamento vem de 20% dos clientes', '80% dos vendedores são bons', '80% das vendas são cash'], 1,
                        'Princípio de Pareto: poucos clientes-chave geram a maior parte do resultado. Foque neles.'],
                    ['Quando o cliente diz "está caro", o correto é:',
                        ['Baixar o preço na hora', 'Perguntar "caro comparado a quê?" e mostrar valor', 'Insistir que é justo', 'Desistir da venda'], 1,
                        'Nunca reduza preço na primeira objeção. Entenda o comparativo e reforce o valor entregue.'],
                    ['Follow-up significa:',
                        ['Seguir o cliente nas redes', 'Contato posterior para acompanhar o interesse/venda', 'Fazer relatório', 'Substituir o produto'], 1,
                        'Follow-up = manter contato após primeira abordagem. Maioria das vendas exige 5+ contatos.'],
                    ['Um "lead" é:',
                        ['Um cliente antigo', 'Um contato interessado, potencial comprador', 'Um vendedor iniciante', 'Um chefe de equipe'], 1,
                        'Lead = prospect que demonstrou interesse (baixou material, preencheu form, etc.).'],
                    ['Cross-sell significa:',
                        ['Vender produto mais caro', 'Vender produto complementar (ex: capinha ao vender celular)', 'Vender para concorrente', 'Vender pelo cruzamento de listas'], 1,
                        'Cross-sell = venda complementar. Up-sell = vender versão mais cara/completa.'],
                    ['Ao apresentar preço, a técnica do "sanduíche" é:',
                        ['Falar rápido', 'Benefício → Preço → Benefício', 'Preço → Silêncio → Espera', 'Só o preço direto'], 1,
                        'Amortece o impacto: destaca valor antes e depois do preço, evitando foco só no custo.'],
                    ['Gatilho mental da "escassez" é ético quando:',
                        ['Você inventa que só tem 1', 'Realmente há estoque limitado ou prazo real', 'Todo dia diz "última unidade"', 'Nunca é ético'], 1,
                        'Escassez real (fim de estoque, oferta com prazo) é ética. Escassez falsa é manipulação.'],
                    ['Ao fazer prospecção fria (cold call), o objetivo primário é:',
                        ['Fechar a venda na hora', 'Agendar uma reunião/próximo passo', 'Enviar catálogo', 'Cumprir cota de ligações'], 1,
                        'Cold call raramente fecha na hora. O objetivo é gerar interesse e agendar próxima etapa.'],
                    ['A pergunta "Quando você gostaria de começar?" é:',
                        ['Muito invasiva', 'Fechamento presumido — muito eficaz', 'Errada gramaticalmente', 'Só para vendas B2B'], 1,
                        'Fechamento presumido: parte do princípio de que já vai fechar. Técnica clássica.'],
                    ['Se um cliente objeta "preciso pensar", o correto é:',
                        ['Aceitar e ir embora', 'Perguntar "sobre o que especificamente você precisa pensar?"', 'Insistir agressivamente', 'Baixar preço para forçar decisão'], 1,
                        '"Preciso pensar" geralmente esconde outra objeção. Descubra qual.'],
                    ['CAC (Custo de Aquisição de Cliente) é:',
                        ['Quanto o cliente gasta', 'Quanto a empresa gasta para conquistar cada novo cliente', 'Comissão do vendedor', 'Custo do estoque'], 1,
                        'CAC = marketing + vendas ÷ clientes conquistados. LTV precisa ser > CAC para ser lucrativo.'],
                    ['LTV (Lifetime Value) é:',
                        ['Anos que o cliente tem', 'Total que o cliente gasta com a empresa ao longo do tempo', 'Valor do estoque', 'Preço médio'], 1,
                        'LTV = quanto um cliente rende no total do relacionamento. Guia decisões de retenção.'],
                    ['Rapport significa:',
                        ['Relatório de vendas', 'Conexão de confiança com o cliente', 'Formulário oficial', 'Reembolso rápido'], 1,
                        'Rapport = sintonia. Você "espelha" postura, ritmo, vocabulário. Base de qualquer venda.'],
                    ['Um vendedor consultivo, ao invés de "empurrar" produto:',
                        ['Diagnostica a necessidade e recomenda solução', 'Vende sempre o mais caro', 'Segue script fechado', 'Só atende quem chega'], 0,
                        'Venda consultiva = ouvir mais que falar. Você vira consultor, não empurra.'],
                    ['Objeção de PREÇO geralmente esconde:',
                        ['Falta de dinheiro', 'Falta de percepção de valor', 'Concorrência mais barata', 'Todas as anteriores'], 3,
                        'Preço é a objeção que mais aparece — e quase sempre encobre outra causa real.'],
                    ['Ao fazer uma proposta comercial escrita, você deve incluir:',
                        ['Só o preço', 'Escopo, prazo, condições, preço e diferenciais', 'Só o produto', 'Preço e forma de pagamento'], 1,
                        'Proposta completa reduz idas-e-vindas. Escopo bem definido evita conflitos futuros.'],
                    ['A "curva ABC" de clientes serve para:',
                        ['Ordem alfabética', 'Classificar clientes por importância no faturamento', 'Notas escolares', 'Categorias de produtos'], 1,
                        'A = clientes-chave (poucos, alto valor). B = médios. C = muitos, baixo valor.'],
                    ['O "elevator pitch" é:',
                        ['Descida em elevador', 'Apresentação da empresa/produto em 30-60s', 'Reunião de alto escalão', 'Discurso de encerramento'], 1,
                        'Elevator pitch = você tem o tempo de um elevador para engajar. Exige preparo e clareza.'],
                    ['Após ganhar uma venda, o próximo passo mais importante é:',
                        ['Esquecer o cliente', 'Fazer pós-venda para gerar recompra e indicações', 'Aumentar preço para próxima', 'Mudar de segmento'], 1,
                        'Custa 5-25x menos manter cliente que conquistar novo. Pós-venda é ouro.'],
                ],
            ],

            /* ============================================================
             |  8) COMUNICAÇÃO PROFISSIONAL
             |============================================================ */
            [
                'title' => 'Comunicação Profissional',
                'slug'  => 'comunicacao-profissional',
                'category' => 'Comunicação',
                'short_description' => 'E-mails, reuniões, WhatsApp corporativo e etiqueta empresarial.',
                'description' => 'Escrita profissional (e-mail, memorando), comunicação oral, apresentações, feedback e etiqueta no ambiente corporativo.',
                'difficulty' => 'basic',
                'icon' => 'message', 'color' => 'blue',
                'questions' => [
                    ['Ao enviar e-mail para um cliente pela primeira vez, o correto é:',
                        ['"Fala aí, blz?"', '"Prezado(a) Sr(a)., ..."', '"E aí, tudo bom?"', '"Oi cliente"'], 1,
                        'Formalidade é regra em primeiro contato. Depois pode-se ajustar ao tom do interlocutor.'],
                    ['Um assunto de e-mail eficaz é:',
                        ['"Importante"', '"Proposta comercial - Cliente X - Ref. 2026-03"', '"Bom dia"', '(deixar em branco)'], 1,
                        'Assunto específico ajuda a priorizar e encontrar depois. Assuntos vagos são ignorados.'],
                    ['CC e CCO em e-mails significam:',
                        ['Com cópia / Com cópia oculta', 'Cliente Chefe / Cópia Chefe Oculto', 'Copiar / Cortar', 'Conta corrente / Cadastro'], 0,
                        'CC (todos veem os destinatários). CCO (os outros não sabem que você recebeu cópia).'],
                    ['Ao usar "Responder a todos" você deve:',
                        ['Sempre usar', 'Usar só quando todos precisam saber da resposta', 'Nunca usar', 'Só em e-mails internos'], 1,
                        'Ficar respondendo a todos gera "poluição". Use apenas quando faz sentido para o grupo.'],
                    ['Numa reunião, chegar 10 minutos atrasado é:',
                        ['Aceitável, todos atrasam', 'Falta grave — sempre avise se vai atrasar', 'Ok se você é chefe', 'Depende do humor'], 1,
                        'Pontualidade é respeito ao tempo dos outros. Se atrasar for inevitável, avise ANTES.'],
                    ['Ao apresentar um slide com muito texto:',
                        ['Leia tudo em voz alta', 'Simplifique — poucas palavras, você fala o resto', 'Adicione mais texto', 'Diminua a fonte'], 1,
                        'Regra 6x6: máximo 6 linhas por slide, 6 palavras por linha. Você é o show, não o slide.'],
                    ['No WhatsApp corporativo, o horário adequado para mensagens é:',
                        ['A qualquer hora', 'Horário comercial, exceto emergências reais', '24 horas', 'Só de manhã'], 1,
                        'Respeite descanso e vida pessoal. Se for urgente, avise por telefone.'],
                    ['Feedback construtivo deve ser:',
                        ['Público, para todos aprenderem', 'Privado, específico e focado em comportamento (não pessoa)', 'Anônimo', 'Só quando algo dá errado'], 1,
                        'Elogio em público, crítica em privado. Foque no ato, não na pessoa ("você fez X" ≠ "você é X").'],
                    ['A técnica "sanduíche" para dar feedback é:',
                        ['Elogio → Crítica → Elogio', 'Crítica → Elogio → Crítica', 'Só elogios', 'Só críticas'], 0,
                        'Elogio real → ponto de melhora → estímulo. Torna o feedback mais fácil de aceitar.'],
                    ['Ao escrever mensagens rápidas no chat da empresa:',
                        ['Use gírias sempre', 'Seja claro e respeitoso, sem tantas abreviações', 'Escreva em CAIXA ALTA', 'Só emojis'], 1,
                        'Chat corporativo pede clareza. Abreviações excessivas ("vc", "tb", "hj") demonstram desleixo.'],
                    ['Se você discorda do seu chefe numa reunião, o correto é:',
                        ['Ficar quieto', 'Contestar publicamente e agressivamente', 'Levantar o ponto com respeito e argumento', 'Sair da sala'], 2,
                        'Divergir é saudável, mas com dados, respeito e no momento certo. Nunca ataque a pessoa.'],
                    ['Um e-mail deve ser encerrado com:',
                        ['"Beijos"', '"Att." ou "Atenciosamente" + nome + cargo', 'Só "tchau"', 'Sem nada'], 1,
                        'Fechamento profissional: assinatura completa (nome, cargo, empresa, contato).'],
                    ['Escuta ativa em reunião significa:',
                        ['Ouvir e simular concordar', 'Prestar atenção real, parafrasear e fazer perguntas', 'Mexer no celular', 'Anotar sem prestar atenção'], 1,
                        'Escuta ativa = você reformula o que ouviu ("então você quer X?") para confirmar entendimento.'],
                    ['Ao lidar com uma pessoa difícil no trabalho:',
                        ['Confrontar de volta', 'Manter profissionalismo, focar em fatos, evitar levar para o pessoal', 'Fofocar', 'Fingir que não é com você'], 1,
                        'Nunca desça ao nível. Documente, foque em fatos, e envolva RH se persistir.'],
                    ['A frase "Como você viu, os números caíram..." em vez de "Você errou os números..." usa:',
                        ['Passivo-agressivo', 'Linguagem observacional (foca no fato, não na culpa)', 'Fofoca', 'Erro gramatical'], 1,
                        'Comunicação não-violenta: observe fatos, expresse sentimento, faça pedido. Reduz defensividade.'],
                    ['Numa apresentação, o "gancho" (hook) inicial serve para:',
                        ['Prender atenção nos primeiros segundos', 'Rir do público', 'Enrolar', 'Pedir permissão'], 0,
                        'Começar com uma história, dado surpreendente ou pergunta prende a plateia. Sem gancho, perde-se.'],
                    ['Se você comete um erro público, o certo é:',
                        ['Esconder', 'Assumir, pedir desculpas específicas e propor correção', 'Culpar outro', 'Fingir que não ocorreu'], 1,
                        'Assumir erro fortalece credibilidade. Culpar outros destrói confiança da equipe.'],
                    ['Uma reunião produtiva tem:',
                        ['Duas horas mínimo', 'Pauta definida, horário limite, decisões registradas', 'Todo mundo da empresa', 'Sem pauta, para ser livre'], 1,
                        'Sem pauta clara, reunião vira conversa. Sempre defina objetivo, tempo e responsáveis.'],
                    ['Se você não sabe uma resposta em reunião, o melhor é dizer:',
                        ['"Sei sim!" (chutando)', '"Não sei, mas apuro e retorno até amanhã"', '"Depois eu vejo"', 'Ficar quieto'], 1,
                        'Fingir saber destrói credibilidade quando descobrem. Assumir + prazo é maduro.'],
                    ['Ao enviar arquivo grande por e-mail:',
                        ['Anexar direto (2 GB)', 'Usar link do Drive/OneDrive e enviar só o link', 'Zipar em várias partes', 'Enviar pelo WhatsApp'], 1,
                        'Anexos > 10MB podem ser barrados. Nuvem (Drive/OneDrive) é padrão corporativo.'],
                ],
            ],

            /* ============================================================
             |  9) LINKEDIN NA PRÁTICA
             |============================================================ */
            [
                'title' => 'LinkedIn na Prática',
                'slug'  => 'linkedin-na-pratica',
                'category' => 'Carreira',
                'short_description' => 'Perfil que atrai recrutadores, networking e busca de vagas eficiente.',
                'description' => 'Domine o LinkedIn: foto e headline que convertem, palavras-chave de busca, conteúdo, networking e InMail.',
                'difficulty' => 'basic',
                'icon' => 'user', 'color' => 'blue',
                'questions' => [
                    ['A foto ideal do LinkedIn é:',
                        ['Selfie no espelho', 'Rosto centralizado, fundo neutro, boa iluminação', 'Foto de festa', 'Sem foto é melhor'], 1,
                        'Foto profissional aumenta visualizações em 14x. Rosto claro, sorriso, fundo neutro.'],
                    ['O "headline" (título) no LinkedIn deve ter:',
                        ['Só o cargo atual', 'Cargo + valor que você gera + palavras-chave da área', 'Frase motivacional', '"Aberto a oportunidades"'], 1,
                        'Headline é o que aparece em toda busca. Combine cargo + resultado + palavra-chave.'],
                    ['A seção "Sobre" (about) deve ter no mínimo:',
                        ['1 frase', '2-3 parágrafos com trajetória, especialidade e resultado', '10 linhas de emojis', 'Só link do e-mail'], 1,
                        'Espaço nobre. Conte quem é, o que faz, resultados e como pode ajudar (com palavras-chave).'],
                    ['Endorsements são:',
                        ['Recomendações escritas', 'Confirmações rápidas das suas skills por conexões', 'Convites para vagas', 'Anúncios pagos'], 1,
                        'Endorsement = 1 clique confirmando "sim, ele sabe X". Sobem as skills nas buscas.'],
                    ['Um "InMail" no LinkedIn é:',
                        ['E-mail interno da empresa', 'Mensagem paga para quem não é sua conexão', 'Notificação', 'Post patrocinado'], 1,
                        'InMail é ferramenta paga (LinkedIn Premium) para falar com quem não é conexão. Recrutadores usam.'],
                    ['Ao aceitar/enviar convite de conexão, o correto é:',
                        ['Enviar em massa sem contexto', 'Personalizar mensagem explicando o motivo', 'Só pedir emprego direto', 'Nunca aceitar desconhecidos'], 1,
                        'Convite com mensagem tem 3x mais aceite. Nunca peça emprego no primeiro contato.'],
                    ['O algoritmo do LinkedIn prioriza posts com:',
                        ['Muitos links externos', 'Engajamento nas primeiras horas (comentários > curtidas)', 'Só imagens', 'Textos curtos'], 1,
                        'Comentários > curtidas > compartilhamentos. Nas primeiras 1-2h define alcance total.'],
                    ['Buscas booleanas no LinkedIn Recruiter usam:',
                        ['Só nomes', 'AND, OR, NOT com aspas e parênteses', 'Emojis', 'Cores'], 1,
                        'Ex: ("dev" OR "developer") AND Laravel NOT junior → filtra candidatos precisos.'],
                    ['O status "Open to Work" (moldura verde) fica visível:',
                        ['Para todos', 'Só para recrutadores (opcional público)', 'Só amigos', 'Nunca'], 1,
                        'Você escolhe: público (com moldura) ou só recrutadores. Recomenda-se só recrutadores.'],
                    ['A frequência ideal para postar no LinkedIn é:',
                        ['3x por dia', '2-4 vezes por semana com conteúdo relevante', 'Todo dia às 9h', '1x por mês'], 1,
                        'Consistência > frequência. 2-4 posts semanais com valor real funcionam melhor.'],
                    ['Um bom post no LinkedIn começa com:',
                        ['Link direto', 'Um gancho que faz o leitor querer continuar (primeira linha)', '"Curtam por favor"', 'Hashtag'], 1,
                        'LinkedIn corta o post e mostra só a primeira linha. Ela define se você é lido.'],
                    ['Ao pedir uma recomendação, o correto é:',
                        ['Enviar template pronto', 'Personalizar por pessoa, lembrar contexto do trabalho', 'Pedir sem contexto', 'Só para chefes'], 1,
                        'Diga em qual projeto trabalharam, quais skills destacar. Facilita para quem vai escrever.'],
                    ['Palavras-chave importam porque:',
                        ['LinkedIn cobra por elas', 'Recrutadores buscam por termos específicos ("PHP", "gerente de vendas")', 'Sobem o preço da vaga', 'Não importam'], 1,
                        'Sem as palavras-chave certas você é invisível na busca dos recrutadores.'],
                    ['A "Prova social" no LinkedIn vem de:',
                        ['Número de conexões', 'Recomendações + endorsements + engajamento nos posts', 'Só do cargo atual', 'Foto bonita'], 1,
                        'Terceiros validando você > você falar de você. Recomendação escrita é ouro.'],
                    ['Ao mudar de emprego, você deve:',
                        ['Não atualizar', 'Atualizar cargo/empresa e ativar notificação para conexões', 'Deletar histórico antigo', 'Criar perfil novo'], 1,
                        'Aviso "Comecei em X" gera engajamento e amplia sua visibilidade.'],
                    ['Um perfil "All-Star" (nível máximo) exige:',
                        ['1 conexão', 'Foto, sobre completo, 50+ conexões, cargo atual, formação, skills', 'Pagar Premium', 'Só experiência'], 1,
                        'LinkedIn Skill Assessments + perfil completo aparece 40x mais em buscas.'],
                    ['Skill Assessments (badges do LinkedIn) servem para:',
                        ['Cobrar pelas skills', 'Provar tecnicamente uma habilidade (LinkedIn testa você)', 'Convidar conexões', 'Nada útil'], 1,
                        'Passa em teste (top 30%), ganha badge. Recrutadores filtram por skills verificadas.'],
                    ['Ao responder um recrutador que se interessou:',
                        ['Só emoji "obrigado"', 'Agradecer, mostrar interesse, marcar próxima conversa', 'Enviar CV sem mais', 'Ignorar'], 1,
                        'Trate cada contato como uma entrevista. Resposta rápida e educada abre portas.'],
                    ['O melhor dia/horário para postar no LinkedIn geralmente é:',
                        ['Domingo à noite', 'Terça-quinta, entre 8h-12h', 'Sábado', 'Não importa'], 1,
                        'B2B roda em horário comercial. Segunda começa devagar, sexta desacelera.'],
                    ['SSI (Social Selling Index) mede:',
                        ['Vendas totais', 'Sua eficácia de vender/networkar no LinkedIn (0-100)', 'Índice de spam', 'Média de curtidas'], 1,
                        'SSI de 70+ é considerado excelente. Aparece em linkedin.com/sales/ssi (gratuito).'],
                ],
            ],

            /* ============================================================
             |  10) ROTINAS ADMINISTRATIVAS
             |============================================================ */
            [
                'title' => 'Rotinas Administrativas',
                'slug'  => 'rotinas-administrativas',
                'category' => 'Administrativo',
                'short_description' => 'Documentos, arquivamento, agenda, controles e organização de escritório.',
                'description' => 'Base do trabalho administrativo: emissão de documentos, arquivamento, controle de contas a pagar/receber, agenda e etiqueta corporativa.',
                'difficulty' => 'basic',
                'icon' => 'briefcase', 'color' => 'accent',
                'questions' => [
                    ['O CNPJ tem quantos dígitos (incluindo pontuação)?',
                        ['11', '14 (números) / 18 com pontuação', '15', '12'], 1,
                        'CNPJ: XX.XXX.XXX/XXXX-XX → 14 números, 18 caracteres com pontuação.'],
                    ['Uma nota fiscal deve ser arquivada por quantos anos (regra geral)?',
                        ['1 ano', '5 anos (fiscal)', '10 anos', 'Sempre'], 1,
                        'Documentos fiscais: 5 anos. Trabalhistas: 5 anos após rescisão. FGTS: 30 anos.'],
                    ['O que é um "boleto bancário"?',
                        ['Sinônimo de cheque', 'Documento de cobrança pagável em qualquer banco', 'Extrato bancário', 'Cartão de crédito'], 1,
                        'Boleto tem código de barras, valor, vencimento e pode ser pago em qualquer instituição.'],
                    ['Uma "circular" interna é:',
                        ['Documento externo', 'Comunicado interno enviado a vários colaboradores', 'Contrato de venda', 'Nota fiscal'], 1,
                        'Circular = documento interno padronizado para várias pessoas. Formal, com número/data.'],
                    ['Ao arquivar documentos, o método mais comum é:',
                        ['Ordem aleatória', 'Alfabético, cronológico ou numérico', 'Por cor', 'Por peso'], 1,
                        'Método depende do volume: alfabético (contatos), cronológico (extratos), numérico (NFs).'],
                    ['DDA (Débito Direto Autorizado) é:',
                        ['Desconto de imposto', 'Sistema que centraliza boletos no banco', 'Débito automático', 'Dinheiro em conta'], 1,
                        'DDA agrupa boletos da empresa no internet banking. Facilita gestão de contas a pagar.'],
                    ['Um "protocolo" na recepção de documentos serve para:',
                        ['Enfeitar', 'Registrar entrada com data/hora — prova de recebimento', 'Substituir NF', 'Contar produtos'], 1,
                        'Protocolo é prova de que documento foi entregue e quando. Fundamental em prazos.'],
                    ['Prazo para pagamento de INSS da empresa (regra geral):',
                        ['Até dia 5 do mês', 'Até dia 20 do mês seguinte ao fato gerador', 'Trimestral', 'Anual'], 1,
                        'INSS patronal: até dia 20 do mês seguinte. Se cair em feriado, antecipa.'],
                    ['O que é uma "fatura" em telefonia/energia?',
                        ['Boleto', 'Documento com detalhamento de consumo e valor a pagar', 'Contrato', 'Recibo de pagamento'], 1,
                        'Fatura detalha o consumo do período. Pode vir com boleto anexo para pagamento.'],
                    ['Ao enviar documento por Sedex, você deve:',
                        ['Só colocar endereço', 'Preencher AR, guardar código de rastreio', 'Enviar sem controle', 'Só usar carta comum'], 1,
                        'AR (Aviso de Recebimento) prova entrega. Rastreio permite acompanhar até destinatário.'],
                    ['Um "livro de protocolo" registra:',
                        ['Estoque', 'Entrada e saída de documentos com assinatura', 'Vendas', 'Reuniões'], 1,
                        'Cada documento recebido/entregue é registrado (data, hora, quem entregou). Auditoria pode pedir.'],
                    ['A sigla RH significa:',
                        ['Registro Humano', 'Recursos Humanos', 'Renda Habitual', 'Recibo Hipotecário'], 1,
                        'Recursos Humanos: setor que cuida de contratação, folha, benefícios, treinamento.'],
                    ['Contas a pagar de vencimento próximo devem ser:',
                        ['Ignoradas', 'Priorizadas no fluxo de caixa e agendadas', 'Pagas só no fim do mês', 'Pagas apenas se der'], 1,
                        'Atraso gera multa, juros, restrição. Fluxo de caixa organiza o que pagar quando.'],
                    ['Ao agendar reunião para o chefe, o correto é:',
                        ['Só marcar', 'Confirmar disponibilidade, sala, e enviar convite com pauta', 'Ligar para o outro', 'Só mandar SMS'], 1,
                        'Reunião com pauta rende mais. Convite Outlook/Google reserva agenda automaticamente.'],
                    ['Papel timbrado é usado quando:',
                        ['Nunca mais', 'Correspondência oficial da empresa (contratos, ofícios)', 'Documento interno', 'Rascunho'], 1,
                        'Papel timbrado dá formalidade e valor institucional a documentos oficiais.'],
                    ['Ao redigir um ofício, a estrutura básica inclui:',
                        ['Só o texto', 'Timbre + destinatário + saudação + corpo + fecho + assinatura', 'Só assinatura', 'Assunto e texto'], 1,
                        'Ofício segue padrão formal: cabeçalho, número, data, destinatário, texto, fecho.'],
                    ['O que é "conciliação bancária"?',
                        ['Sinônimo de contrato', 'Comparação do extrato bancário com registros internos da empresa', 'Empréstimo', 'Investimento'], 1,
                        'Conciliação = confere se o que o banco mostra bate com contas a pagar/receber. Detecta erros/fraudes.'],
                    ['Kanban é útil para:',
                        ['Contar dinheiro', 'Visualizar tarefas em colunas (a fazer, fazendo, feito)', 'Enviar e-mail', 'Arquivar papel'], 1,
                        'Kanban dá visão do fluxo de trabalho. Trello, Notion, Jira usam esse conceito.'],
                    ['Ao organizar arquivos digitais em pastas, o melhor é:',
                        ['Tudo na área de trabalho', 'Estrutura clara (Ano > Cliente > Tipo) + nomes padrão', 'Nomes aleatórios', 'Não organizar'], 1,
                        'Estrutura padronizada acelera busca em anos. Ex: 2026 > ClienteA > Contratos.'],
                    ['O que faz um "assistente administrativo"?',
                        ['Só faz café', 'Suporte operacional: documentos, agenda, atendimento, controles', 'Vende produtos', 'Programa softwares'], 1,
                        'Cargo-chave: mistura documentação, atendimento, agenda, contas — quem faz a "casa" rodar.'],
                ],
            ],
        ];
    }
}
